[2023-07-02T08:24:30.499+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-02T08:24:29.703225+00:00 [queued]>
[2023-07-02T08:24:30.505+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-02T08:24:29.703225+00:00 [queued]>
[2023-07-02T08:24:30.506+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-02T08:24:30.514+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-07-02 08:24:29.703225+00:00
[2023-07-02T08:24:30.518+0000] {standard_task_runner.py:57} INFO - Started process 152 to run task
[2023-07-02T08:24:30.522+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-07-02T08:24:29.703225+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp52ri2dqk']
[2023-07-02T08:24:30.523+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load_seed_data_once
[2023-07-02T08:24:30.567+0000] {task_command.py:410} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-02T08:24:29.703225+00:00 [running]> on host 7f1ae188f5a7
[2023-07-02T08:24:30.646+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1_init_once_seed_data' AIRFLOW_CTX_TASK_ID='load_seed_data_once' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T08:24:29.703225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T08:24:29.703225+00:00'
[2023-07-02T08:24:30.647+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-02T08:24:30.648+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2023-07-02T08:24:30.656+0000] {subprocess.py:86} INFO - Output:
[2023-07-02T08:24:32.190+0000] {subprocess.py:93} INFO - [0m08:24:32  Running with dbt=1.5.2
[2023-07-02T08:24:32.192+0000] {subprocess.py:93} INFO - [0m08:24:32  Encountered an error:
[2023-07-02T08:24:32.193+0000] {subprocess.py:93} INFO - Runtime Error
[2023-07-02T08:24:32.193+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /dbt/dbt_project.yml
[2023-07-02T08:24:32.194+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-02T08:24:32.194+0000] {subprocess.py:93} INFO - 
[2023-07-02T08:24:32.823+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-02T08:24:32.835+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-02T08:24:32.838+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230702T082429, start_date=20230702T082430, end_date=20230702T082432
[2023-07-02T08:24:32.847+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 5 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 152)
[2023-07-02T08:24:32.857+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T08:24:32.873+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
