[2023-07-09T06:53:27.358+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: seed_library_data.load_seed_data_once manual__2023-07-09T06:53:26.905476+00:00 [queued]>
[2023-07-09T06:53:27.364+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: seed_library_data.load_seed_data_once manual__2023-07-09T06:53:26.905476+00:00 [queued]>
[2023-07-09T06:53:27.365+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T06:53:27.374+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-07-09 06:53:26.905476+00:00
[2023-07-09T06:53:27.377+0000] {standard_task_runner.py:57} INFO - Started process 115 to run task
[2023-07-09T06:53:27.380+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'seed_library_data', 'load_seed_data_once', 'manual__2023-07-09T06:53:26.905476+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/seed_library.py', '--cfg-path', '/tmp/tmpdp0pb5h1']
[2023-07-09T06:53:27.381+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask load_seed_data_once
[2023-07-09T06:53:27.423+0000] {task_command.py:410} INFO - Running <TaskInstance: seed_library_data.load_seed_data_once manual__2023-07-09T06:53:26.905476+00:00 [running]> on host b04aa736c938
[2023-07-09T06:53:27.501+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='seed_library_data' AIRFLOW_CTX_TASK_ID='load_seed_data_once' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T06:53:26.905476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T06:53:26.905476+00:00'
[2023-07-09T06:53:27.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-09T06:53:27.503+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /library_dim_model && dbt seed --profiles-dir .']
[2023-07-09T06:53:27.512+0000] {subprocess.py:86} INFO - Output:
[2023-07-09T06:53:27.514+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /library_dim_model: No such file or directory
[2023-07-09T06:53:27.514+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-09T06:53:27.525+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-09T06:53:27.528+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=seed_library_data, task_id=load_seed_data_once, execution_date=20230709T065326, start_date=20230709T065327, end_date=20230709T065327
[2023-07-09T06:53:27.536+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 38 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 1.; 115)
[2023-07-09T06:53:27.553+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T06:53:27.570+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
