[2023-07-09T06:59:51.898+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T06:59:51.479948+00:00 [queued]>
[2023-07-09T06:59:51.904+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T06:59:51.479948+00:00 [queued]>
[2023-07-09T06:59:51.904+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T06:59:51.912+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-07-09 06:59:51.479948+00:00
[2023-07-09T06:59:51.916+0000] {standard_task_runner.py:57} INFO - Started process 651 to run task
[2023-07-09T06:59:51.919+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-07-09T06:59:51.479948+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp6gyi88pj']
[2023-07-09T06:59:51.919+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask load_seed_data_once
[2023-07-09T06:59:51.957+0000] {task_command.py:410} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T06:59:51.479948+00:00 [running]> on host b04aa736c938
[2023-07-09T06:59:52.035+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1_init_once_seed_data' AIRFLOW_CTX_TASK_ID='load_seed_data_once' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T06:59:51.479948+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T06:59:51.479948+00:00'
[2023-07-09T06:59:52.036+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-09T06:59:52.037+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2023-07-09T06:59:52.045+0000] {subprocess.py:86} INFO - Output:
[2023-07-09T06:59:53.466+0000] {subprocess.py:93} INFO - [0m06:59:53  Running with dbt=1.5.2
[2023-07-09T06:59:53.469+0000] {subprocess.py:93} INFO - [0m06:59:53  Encountered an error:
[2023-07-09T06:59:53.469+0000] {subprocess.py:93} INFO - Runtime Error
[2023-07-09T06:59:53.470+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /dbt/dbt_project.yml
[2023-07-09T06:59:53.471+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-09T06:59:53.472+0000] {subprocess.py:93} INFO - 
[2023-07-09T06:59:54.150+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-09T06:59:54.162+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-09T06:59:54.165+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230709T065951, start_date=20230709T065951, end_date=20230709T065954
[2023-07-09T06:59:54.174+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 40 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 651)
[2023-07-09T06:59:54.190+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T06:59:54.205+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
